### ISSUE TITLE
Bug: CognitoIdentityID is empty on Lambda invoke of GO function

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-lambda-go#46]
The CognitoIdentityID field in the lambda context structure for Go seems not to be working. These are direct invocations of lambda functions forwarded from Cloudfront. API Gateway is not being used.

I am sure the CognitoIdentity is part of my request, direct lambda calls are protected by IAM security.  So I had to get through the IAM encryption check in order to invoke the lambda. I dumped my context.Context from go:
```
{
    "AwsRequestID": "92db745e-183c-11e8-be7d-c53e91fb11c8",
    "InvokedFunctionArn": "arn:aws:lambda:us-east-1:xxxxx:function:digi2API-dev-world",
    "Identity": {
        "CognitoIdentityID": "",
        "CognitoIdentityPoolID": ""
    },
    "ClientContext": {
        "Client": {
            "installation_id": "",
            "app_title": "",
            "app_version_code": "",
            "app_package_name": ""
        },
        "env": null,
        "custom": null
    }
}
````
When I make a similar call from the same front-end to a lambda written in node.js, the context looks like this, only change was editing the function name to call a different lambda.
```
{
    "callbackWaitsForEmptyEventLoop": true,
    "logGroupName": "/aws/lambda/digiAPI-dev-items",
    "logStreamName": "2018/02/21/[$LATEST]a8178cf4ab4a4108b285267bddd9a5d6",
    "functionName": "digiAPI-dev-items",
    "memoryLimitInMB": "512",
    "functionVersion": "$LATEST",
    "identity": {
        "cognitoIdentityId": "us-east-1:73134712-adbb-4432-8cfe-246a8eae6fab",
        "cognitoIdentityPoolId": "us-east-1:4f3f4619-737b-41ed-b0dd-8875cfcf27ab"
    },
    "invokeid": "e8e1d8dc-175e-11e8-a83c-39c3312d1082",
    "awsRequestId": "e8e1d8dc-175e-11e8-a83c-39c3312d1082",
    "invokedFunctionArn": "arn:aws:lambda:us-east-1:xxxxxxxx:function:digiAPI-dev-items
}
```

The example for this in the documentation also does not work for the same reason. Note the variable name is misspelled in the documentation.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-dg.pdf

```
Accessing Invoke Context Information
Lambda functions have access to metadata about their environment and the invocation request. This
can be accessed at Package context. Should your handler include context.Context as a parameter,
Lambda will insert information about your function into the context's Value property. Note that you
need to import the lambdacontext library to access the contents of the context.Context object.
package main
import (
 "context"
 "log"
 "github.com/aws/aws-lambda-go/lambda"
 "github.com/aws/aws-lambda-go/lambdacontext"
)
func CognitoHandler(ctx context.Context) {
 lc, _ := lambdacontext.FromContext(ctx)
 log.Print(lc.Identity.CognitoPoolID)
}
func main() {
 lambda.Start(CognitoHandler)
}
In the example above, lc is the variable used to consume the information that the context object
captured and log.Print(lc.Identity.CognitoPoolID) prints that information, in this case, the
CognitoPoolID.

```

**Comment by jonsmirl** [comment]
I've hacked in a fix, aws-lambda-go/lambda/function.go in Invoke() is missing a couple of assignments. I am just starting with Go and can't figure out the correct syntax for adding the assignment in the initializer, but this hack works.

	lc := &lambdacontext.LambdaContext{
		AwsRequestID:       req.RequestId,
		InvokedFunctionArn: req.InvokedFunctionArn,
	}
	lc.Identity.CognitoIdentityID = req.CognitoIdentityId
	lc.Identity.CognitoIdentityPoolID = req.CognitoIdentityPoolId

**Comment by bmoffatt** [comment]
Thanks for reporting this. Fixed with #47

**Comment by surmer** [comment]
Hi I'm still facing this same problem: empty Cognito ID and Cognito Pool ID field. My iOS app is definitely authenticating: I can copy/paste the Authorization token into Postman and call the API, and I get an Unauthorized if I don't authenticate. I have a recent version of aws-lambda-go that includes @jonsmirl's changes.

The following are empty:
func Handler(ctx context.Context, request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	lc, _ := lambdacontext.FromContext(ctx)
	fmt.Printf("AWS Request id: %s\n", lc.AwsRequestID)
	fmt.Println("Context cognito identity id:", lc.Identity.CognitoIdentityID)
	fmt.Println("Context Cognito pool:", lc.Identity.CognitoIdentityPoolID)
	fmt.Println("Request context cognito id:", request.RequestContext.Identity.CognitoIdentityID)

You'll note this is a lambda proxy event handler.

**Comment by celicoo** [comment]
Same here.

**Comment by celicoo** [comment]
@bmoffatt same here.

**Comment by mogweii** [comment]
any news concerning this bug ?

**Comment by ioannist** [comment]
I am using Lambda proxy integration. CognitoIdentityID is empty.
